### ISSUE TITLE
[Android] the app failed to launch

### ISSUE THREAD

**Issue by zimski** [dpa99c/phonegap-launch-navigator#77] opened 2016-07-11 19:38 UTC
Hello,
The cordova app exit after launching
The new build can't resolve method `okhttp3.internal.Internal.callEnqueue`

```
I/dalvikvm( 2268): Could not find method okhttp3.internal.Internal.callEnqueue, referenced from method okhttp3.ws.WebSocketCall.enqueue
W/dalvikvm( 2268): VFY: unable to resolve virtual method 32935: Lokhttp3/internal/Internal;.callEnqueue (Lokhttp3/Call;Lokhttp3/Callback;Z)V
D/dalvikvm( 2268): VFY: replacing opcode 0x6e at 0x000a
W/dalvikvm( 2268): threadid=27: thread exiting with uncaught exception (group=0x84cefb20)
E/AndroidRuntime( 2268): FATAL EXCEPTION: EventThread
E/AndroidRuntime( 2268): Process: com.toncarton.app, PID: 2268
E/AndroidRuntime( 2268): java.lang.NoSuchMethodError: okhttp3.internal.Internal.callEnqueue
E/AndroidRuntime( 2268): 	at okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:73)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Transport$1.run(Transport.java:75)
E/AndroidRuntime( 2268): 	at io.socket.thread.EventThread.exec(EventThread.java:50)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Transport.open(Transport.java:70)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Socket.probe(Socket.java:458)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Socket.onOpen(Socket.java:471)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Socket.onHandshake(Socket.java:512)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Socket.onPacket(Socket.java:485)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Socket.access$900(Socket.java:30)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Socket$5.call(Socket.java:299)
E/AndroidRuntime( 2268): 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.Transport.onPacket(Transport.java:127)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
E/AndroidRuntime( 2268): 	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
E/AndroidRuntime( 2268): 	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
E/AndroidRuntime( 2268): 	at io.socket.thread.EventThread$2.run(EventThread.java:75)
E/AndroidRuntime( 2268): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime( 2268): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime( 2268): 	at java.lang.Thread.run(Thread.java:841)

```

I think we need to update methods name according to the new lib

Thanks for your help

**Comment by dpa99c** [comment] 2016-07-16 20:44
I'm unable to reproduce this issue using the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example). 

The stacktrace you have posted implies that the class `okhttp3.ws.WebSocketCall` is from okhttp@3.3.0 or below, but the class `okhttp3.internal.Internal` is from okhttp@3.4.0 or above:

The exception being thrown is because the method `okhttp3.internal.Internal.callEnqueue` cannot be found. This method is [present in okhttp@3.3.0](https://github.com/square/okhttp/blob/parent-3.3.0/okhttp/src/main/java/okhttp3/internal/Internal.java#L69) but was [removed in okhttp@3.4.0](https://github.com/square/okhttp/blob/parent-3.4.0/okhttp/src/main/java/okhttp3/internal/Internal.java#L69), implying that the version of the class `okhttp3.internal.Internal` being executed is from 3.4.0 or above.

However, the line which invokes `callEnqueue()` (the next one in the stacktrace) is `okhttp3.ws.WebSocketCall.enqueue(WebSocketCall.java:108)`. We can see the method call to `callEnqueue()` is [present in okhttp@3.3.0](https://github.com/square/okhttp/blob/parent-3.3.0/okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java#L108) but it has been [removed in okhttp@3.4.0](https://github.com/square/okhttp/blob/parent-3.4.0/okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java#L108).

This issue may be caused by having multiple differing versions of the [okhttp](https://github.com/square/okhttp) library present in the project. This plugin uses okhttp for geocoding and [specifies version `3+`](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/plugin.xml#L41) . However, if your project were to contain another plugin which contains a pinned version (e.g. okhttp@3.3.0), this may cause the observed error. 

Is it possible you have another plugin installed which specifies a different version of okhttp? You should be able to tell this by inspecting `platforms/android/build.gradle` (or post the contents of that file here).

**Comment by zimski** [comment] 2016-07-17 13:08
Hi,

Thx for the answer.
In my project, okhttp3 is only used by your plugin, I easily fix the issue
by specifying manualy the previous version.
In gradle, when a library is specified with a + at the end, it will take
the last version of the library, and in this case throw the error for the
reason that you have explained.

So in this case, I think you should specify the right version in the
dependency or update the code to handle the new version of the library.

Cheers,

**Comment by dpa99c** [comment] 2016-07-17 14:42
> So in this case, I think you should specify the right version in the
dependency or update the code to handle the new version of the library.

I think you have failed to understand the nature of the error. There is no "update" that this plugin can make for the "new version" of the library because the external API of okhttp has not changed. 

This plugin invokes the [`newCall()` and `execute()`](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/android/LaunchNavigator.java#L1077) API methods, both of which are present in okhttp@3.3.0 ([here](https://github.com/square/okhttp/blob/parent-3.3.0/okhttp/src/main/java/okhttp3/OkHttpClient.java#L344) and [here](https://github.com/square/okhttp/blob/parent-3.3.0/okhttp/src/main/java/okhttp3/Call.java#L44)) and continue to be unchanged in the latest version ([here](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java#L387) and [here](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Call.java#L44)).

> I easily fix the issue by specifying manualy the previous version.

This works in your case because, as previously stated, you appear to have multiple versions of the okhttp library which are overlapping. However, this is not an issue for me: my test project is currently using okhttp@3.4.1 and it works fine.

>In gradle, when a library is specified with a + at the end, it will take
the last version of the library

This is precisely the reason that the plugin specifies `okhttp:3+`. By arbitrarily pinning the version (e.g. to 3.3.0), the plugin will then continue to pull in an outdated version of the library that does not benefit from bug fixes or compatibility patches for new versions of Android that later versions contain.

Since no other users have reported this issue (this plugin is downloaded [thousands of times per month](http://npm-stat.com/charts.html?package=uk.co.workingedge.phonegap.plugin.launchnavigator)), I'm going to close this.

**Closed by dpa99c** 2016-07-17 14:42 UTC
Labels: more info needed
