### ISSUE TITLE
Ionic: Maps won't open

### ISSUE THREAD

**Issue by Giregar** [dpa99c/phonegap-launch-navigator#48] opened 2016-03-04 06:14 UTC
Hi guys,
I'm using the Ionic framework and doing this:

```
$scope.navigate = function() {

    // Ermittelt die eigene Position und gibt die Koordinaten wider
    var posOptions = {timeout: 10000, enableHighAccuracy: false};
    $cordovaGeolocation
      .getCurrentPosition(posOptions)
      .then(function (position) {

        $scope.position = position;

        // Smartphone Koordinaten
        var destination = [
          $scope.position.coords.latitude,
          $scope.position.coords.longitude
        ];

        // Ziel Koordinaten
        var start = [
          $scope.LatLng.lat,
          $scope.LatLng.lng
        ];

        console.log(destination);
        console.log(start);

        launchnavigator.navigate(
          destination,
          start,
          function(){
            alert("Plugin success");
          },
          function(error){
            alert("Plugin error: "+ error);
          },
          {
            navigationMode: "maps"
          }
        );
    
      });
  };

```
Within my app is a button calling the function navigate(), but nothing happens.
What shall I do?

**Comment by dpa99c** [comment] 2016-03-04 17:42
Your usage of the plugin API looks correct. Does the console output show any errors? Alternatively, you can check no exception is being raised by wrapping the call in a try/catch:

    try{
         launchnavigator.navigate(
          destination,
          start,
          function(){
            alert("Plugin success");
          },
          function(error){
            alert("Plugin error: "+ error);
          },
          {
            navigationMode: "maps"
          }
        );
    }catch(e){
        alert("Exception: "+e.message);
    }

**Comment by Giregar** [comment] 2016-03-04 21:54
The error is: **ReferenceError: launchnavigator is not defined**

**Comment by dpa99c** [comment] 2016-03-04 21:55
This means the plugin is not installed properly

**Comment by Giregar** [comment] 2016-03-04 22:05
Removed and reinstalled the plugin, but I got the same error.

**Comment by dpa99c** [comment] 2016-03-04 22:07
See the [example project](https://github.com/dpa99c/phonegap-launch-navigator-example) for a working implementation

**Comment by napcat** [comment] 2016-03-09 16:03
Hello,

I'm also using Ionic and I'm getting the error: "ReferenceError: launchnavigator is not defined".
The app has other plugins and they are installed and working with no problems.

Can it be something related to Ionic or this specific plugin?

**Comment by dpa99c** [comment] 2016-03-09 16:47
Just to confirm, you are actually trying this on a real mobile platform (Android/iOS/Windows) and not in a browser using `ionic serve`? If so, what device/platform/version are you testing?

**Comment by napcat** [comment] 2016-03-09 17:21
Yes, I'm testing it on a device.

After a "ionic run android", I'm debugging the app from the device with the Chrome inspect devices functionality:

    chrome://inspect/#devices

and I'm getting the error: "ReferenceError: launchnavigator is not defined".

I checked the source on the platform folder and the plugin seems to be installed, just the reference is not defined in the javascript. The plugin is called by the user interaction on a button.

The device is a Wiko Rainbow with Android 4.4.2 and the plugin version is the latest 2.9.11.

I have another app based on cordova (but not built with Ionic) and the plugin is working.
The plugin version used it that app is 2.9.5.

**Comment by dpa99c** [comment] 2016-03-09 17:26
I've added an [Ionic example project](https://github.com/dpa99c/phonegap-launch-navigator-example/tree/master/IonicExample) to the [example project repo](https://github.com/dpa99c/phonegap-launch-navigator-example). It illustrates using this plugin both via its classic Cordova plugin API and as a wrapped Angular service.

There's a [pre-compiled APK](https://github.com/dpa99c/phonegap-launch-navigator-example/blob/master/build/IonicExample.apk) of it built using v2.9.11 of the plugin.

**Comment by Giregar** [comment] 2016-03-10 11:05
If I delete my app and reinstall it, Android is asking for permission to locate the device. I accept and the app is crashing. chrome://inspect/#devices and the console just let me know, that launchnavigator isn't defined.
I've another app simple app, without tabs, and the plugin is working fine.

I created a new project, copied the source code to the new one. I thought, there could be some issues with the permissions. But nothing changed. Even the new app didn't work, same errors.

I really don't know what to do... If I find the issue, I'll let you know.

**Comment by dpa99c** [comment] 2016-03-10 13:57
My advice is:
- Cut it back to as simple a test case as possible
- Connect Chrome remote debugging tool and use it to inspect Sources. I'd expect to see that launchnavigator.js is not being included.
- Place a breakpoint on the call to launchnavigator.

However, as the example project illustrates, this isn't a general issue caused by Ionic in conjunction with this plugin, hence I'm closing this as an issue.

**Closed by dpa99c** 2016-03-10 13:57 UTC
