### ISSUE TITLE
Default app can't be reset

### ISSUE THREAD

**Issue by Holbanner** [dpa99c/phonegap-launch-navigator#196] opened 2018-07-03 09:07 UTC
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

When selecting to remember the choice of default app, it is not possible to reset that choice from android parameters afterward.

I've tried opening navigation apps from other apps. When prompted to select the navigation app I choose one then selected to remember my choice. 
After that I could reset that choice by going paramters->applications->{waze/maps/uber/...}->defaults-->remove defaults.
Then when relaunching Navigation from another app i was prompted again with the choice.
When doing this after choosing to remember with the plugin there is no defaults in the navigation app
**Expected behavior:**

Once the default navigation app is remembered it should be resetable through parameters
**Steps to reproduce:**

On any project using launch navigator, start a navigation, select an app, select remember your choice and try to reset that choice so you can reselect it later.
**Environment information**

- Cordova CLI version 
	- 8.0.0
- Cordova platform version
	- android 6.3.0
        -ios 4.5.4
- Plugins & versions installed in project (including this plugin)
    - com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
-cordova-custom-config 4.0.2 "cordova-custom-config"
cordova-open-native-settings 1.5.1 "Native settings"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-brightness 0.1.5 "Brightness"
cordova-plugin-calendar 4.6.0 "Calendar"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-http 1.2.0 "SSL Pinning"
cordova-plugin-inappbrowser 1.6.1 "InAppBrowser"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 2.0.5 "NativeGeocoder"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.1.8 "SocialSharing"
cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.8 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.3 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.3 "Launch Navigator"
- Dev machine OS and version, e.g.
    - OSX
        ProductName:    Mac OS X
        ProductVersion: 10.13.4
        BuildVersion:   17E202
 
_Runtime issue_
- Device details
    - Google Nexus 5, Honor 6X, iphone 6, iPad Mini
- OS details
    - Android 7.1.1, Android 7.0, IOs10.3.3, IOs 11.3	
	
_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.3.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.0

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v10.4.1
    npm        : 6.1.0
    OS         : macOS High Sierra
    Xcode      : Xcode 9.3.1 Build version 9E501

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

- Installed Ionic Native modules and versions
  ├── @ionic-native/app-availability@4.7.0
├── @ionic-native/brightness@4.3.3
├── @ionic-native/calendar@4.7.0
├── @ionic-native/camera@4.7.0
├── UNMET PEER DEPENDENCY @ionic-native/core@4.7.0
├── @ionic-native/date-picker@3.14.0
├── @ionic-native/device@4.7.0
├── @ionic-native/diagnostic@4.7.0
├── @ionic-native/file@4.7.0
├── @ionic-native/file-opener@4.7.0
├── @ionic-native/geolocation@4.7.0
├── @ionic-native/google-maps@4.8.2
├── @ionic-native/http@4.7.0
├── @ionic-native/in-app-browser@4.7.0
├── @ionic-native/keyboard@4.7.0
├── @ionic-native/launch-navigator@4.7.0
├── @ionic-native/location-accuracy@4.7.0
├── @ionic-native/native-geocoder@4.7.0
├── @ionic-native/open-native-settings@4.7.0
├── @ionic-native/push@4.7.0
├── @ionic-native/social-sharing@4.7.0
├── @ionic-native/splash-screen@4.7.0
├── @ionic-native/sqlite@4.7.0
├── @ionic-native/status-bar@4.7.0

</details><br/><br/>

**Other information:**

# Feature request

# Documentation issue

**Comment by dpa99c** [comment] 2018-07-03 10:49
From your description, I'm not quite clear on what the issue is.

Once the user has chosen a preferred app, the remembered choice can be cleared by calling [appSelection.userChoice.clear()](https://github.com/dpa99c/phonegap-launch-navigator#appselectionuserchoiceclear).

Are you saying calling this function on Android isn't clearing the user choice?

**Comment by Holbanner** [comment] 2018-07-03 10:57
Hi,
Not really what i meant. I'll try to be a bit more clear.
I mean that in most case when you select a default app be it to open a map or to open a calendar or to browse the web, if the user feels like changing app he can go to Android/Ios setting page -> go to either a page that is general for default apps or go to a specific app and then choose what default app opens what.

But when i do that with apps using this plugin, I can't manage this setting.

From your answer I kind of understand that the plugin doesn't actually switch the native settings? But rather create a local setting, right?

**Comment by dpa99c** [comment] 2018-07-03 11:01
Yes, the preference is stored locally within the app that contains the plugin. 

I don't know of any native Android/iOS API to enable you to set/clear the default app used by the OS from a 3rd app - I don't think it can be done.

**Comment by Holbanner** [comment] 2018-07-03 11:10
Right, my bad. I misunderstood and thought that the dialog was the native
setting dialog.

Kind of how the plug-in open-native-setting just opens the settings page of
your phone. From memory it could more or less target a precise setting page
so the user could manually switch autorisations for exemple

Le mar. 3 juil. 2018 à 13:01, Dave Alden <notifications@github.com> a
écrit :

**Comment by dpa99c** [comment] 2018-07-03 11:13
> From memory it could more or less target a precise setting page
so the user could manually switch autorisations for exemple

It could, but this requires manual user action, whereas the current implementation allows the preference to be controlled from within the app that's using the plugin: a simple button to clear their current preference. Therefore, I don't see a good reason to switch over to using native settings where the user needs to manually set the preference. On that basis, I will close this as an issue.

**Closed by dpa99c** 2018-07-03 11:13 UTC

**Comment by Holbanner** [comment] 2018-07-03 11:18
Agreed

Le mar. 3 juil. 2018 à 13:13, Dave Alden <notifications@github.com> a
écrit :
