### ISSUE TITLE
Waze force closes on iOS when address is not URL-encoded

### ISSUE THREAD

**Issue by fmsouza** [dpa99c/phonegap-launch-navigator#202] opened 2018-08-27 15:23 UTC
**I'm submitting a ...**  (check one with "x"):
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

When I use this plugin to open `Waze` and navigate to some address string instead of coordinates, the app force closes in IOS environment. Looking at the Waze's documentation for Deeplinks it's possible to see they require the params to be URL-encoded in order to make it work properly.

**Expected behavior:**

When sending an address string as param to the plugin, while selecting `Waze` as the corresponding app, it should open the app with the address set for navigation without problems.

**Steps to reproduce:**

- Create a blank project
- Install this plugin
- Add a button to call the Waze app with an address string as parameter
- Install the app in an iPhone device

**Environment information**

- Cordova CLI version
8.0.0

- Cordova platform version
Installed platforms:
  android 6.4.0
  browser 5.0.3
  ios 4.5.5
Available platforms:
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

- Plugins & versions installed in project (including this plugin)
cordova-android-play-services-gradle-release 1.4.3 "cordova-android-play-services-gradle-release"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-advanced-http 0.0.40 "Advanced HTTP plugin"
cordova-plugin-app-preferences 0.99.3 "AppPreferences"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-broadcaster 3.0.1 "broadcaster"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-google-analytics 1.8.6 "Google Universal Analytics Plugin"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-mauron85-background-geolocation 2.3.5 "CDVBackgroundGeolocation"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-passbook 0.2.1 "Passbook"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.5 "Launch Navigator"

- Dev machine OS and version, e.g.
ProductName:    Mac OS X
ProductVersion: 10.13.6
BuildVersion:   17G65
        
_Runtime issue_
- Device details
    - _iPhone 7, iPhone X_
- OS details
    - _iOS 11.4.1_	
	
_iOS build issue:_
- Node JS version
    - 9.11.1
- XCode version
	- 9.4.1

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
```
Ionic:

   ionic (Ionic CLI)  : 4.0.6 (/Users/fred/.nvm/versions/node/v9.11.1/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : android 6.4.0, browser 5.0.3, ios 4.5.5

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.2
   ios-sim           : 6.1.2
   NodeJS            : v9.11.1 (/Users/fred/.nvm/versions/node/v9.11.1/bin/node)
   npm               : 6.2.0
   OS                : macOS High Sierra
   Xcode             : Xcode 9.4.1 Build version 9F2000

Environment:

   ANDROID_HOME : /Users/fred/Library/Android/sdk
```

- Installed Ionic Native modules and versions
```
├── @ionic-native/app-preferences@4.6.0
├── @ionic-native/background-fetch@4.9.1
├── @ionic-native/background-geolocation@4.9.2
├── @ionic-native/badge@4.10.0
├── @ionic-native/broadcaster@4.6.0
├── @ionic-native/core@4.6.0
├── @ionic-native/deeplinks@4.6.0
├── @ionic-native/diagnostic@4.6.0
├── @ionic-native/geolocation@4.6.0
├── @ionic-native/google-analytics@4.10.0
├── @ionic-native/http@4.6.0
├── @ionic-native/launch-navigator@4.6.0
├── @ionic-native/local-notifications@4.11.0
├── @ionic-native/network@4.6.0
├── @ionic-native/splash-screen@4.6.0
├── @ionic-native/status-bar@4.6.0
```

**Other information:**

The following address works if you call the plugin to open `Google Maps` and `Apple Maps` is both Android and iOS. When calling in `Waze`, it only works on Android, and crashes in iOS.

Address: _NAPA, 116 West 15th Street, Panama City, Florida, 32401, United States_

A potential fix would be sanitizing the URL before completing the Deeplink call. Javascript has functions for that: `encodeURI` and `encodeURIComponent`.

[Waze Deeplink API documentation](https://developers.google.com/waze/deeplinks/) (Look for _Search_ and _Combining parameters_)

**Comment by dpa99c** [comment] 2018-08-28 12:04
This plugin's [iOS implementation of the Waze URL scheme](https://github.com/dpa99c/phonegap-launch-navigator/blob/master/src/ios/LaunchNavigator.m#L449) uses only latitude/longitude coordinate pairs because up until recently Waze did not support combining of the search (`q=`) and navigation (`navigate=yes`) parameters.

Therefore the plugin uses its own internal geocoding method to translate the requested address into coordinates.
On testing the address you have specified, this seems to work fine with the plugin and Waze on iOS:

	2018-08-28 12:52:09.996187+0100 Launch Navigator Simple Example[411:63759] LaunchNavigator[native]: Called navigate() with args: destination=NAPA, 116 West 15th Street, Panama City, Florida, 32401, United States; destType=name; destName=<null>; start=; startType=none; startName=<null>; appName=waze; transportMode=driving; extras=<null>
	2018-08-28 12:52:09.996320+0100 Launch Navigator Simple Example[411:63759] LaunchNavigator[native]: Attempting to geocode address: NAPA, 116 West 15th Street, Panama City, Florida, 32401, United States
	2018-08-28 12:52:10.108027+0100 Launch Navigator Simple Example[411:63759] LaunchNavigator[native]: Geocoded address 'NAPA, 116 West 15th Street, Panama City, Florida, 32401, United States' to coord '30.1756, -85.662'
	2018-08-28 12:52:10.118902+0100 Launch Navigator Simple Example[411:63759] LaunchNavigator[native]: Using waze to navigate to NAPA, 116 West 15th Street, Panama City, Florida, 32401, United States [30.1756, -85.662] from current location
	2018-08-28 12:52:10.119133+0100 Launch Navigator Simple Example[411:63759] LaunchNavigator[native]: Launching URI: waze://?ll=30.175552,-85.661968&navigate=yes

Closing as described issue cannot be reproduced.

**Closed by dpa99c** 2018-08-28 12:04 UTC
