### ISSUE TITLE
After installing this plugin the app fails to build for Ionic

### ISSUE THREAD

**Issue by TitikshaDaga** [dpa99c/phonegap-launch-navigator#166] opened 2017-11-17 06:10 UTC
I am making an ionic app.I wanted to open the default maps app for any device. After installing the plugin i m getting the following error :
/home/power/Ionic_Projects/UrMuv/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugApkCopy'.
   > Could not resolve com.squareup.okhttp3:okhttp:3+.
     Required by:
         project :
      > Could not resolve com.squareup.okhttp3:okhttp:3+.
         > Failed to list versions for com.squareup.okhttp3:okhttp.
            > Unable to load Maven meta-data from https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/maven-metadata.xml.
               > Could not GET 'https://jcenter.bintray.com/com/squareup/okhttp3/okhttp/maven-metadata.xml'.
                  > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.161.20.85, jcenter.bintray.com/52.34.155.241] failed: Connection refused (Connection refused)
      > Could not resolve com.squareup.okhttp3:okhttp:3+.
         > Failed to list versions for com.squareup.okhttp3:okhttp.
            > Unable to load Maven meta-data from https://maven.google.com/com/squareup/okhttp3/okhttp/maven-metadata.xml.
               > Could not GET 'https://maven.google.com/com/squareup/okhttp3/okhttp/maven-metadata.xml'.
                  > Connect to maven.google.com:443 [maven.google.com/216.58.196.99] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

[ERROR] An error occurred while running cordova run android --device (exit code 
        1).

**Comment by dpa99c** [comment] 2017-11-17 08:51
As the error states, the problem is that the Gradle build tool was unable to reach the Google Maven server in order to download `okhttp`, an HTTP client library that the plugin uses and therefore depends on.

If you have a firewall running, check it's not blocking this connection.
If you're going through a proxy, you'll need to configure Gradle to use it - [see here](https://stackoverflow.com/q/30219065/777265).

Closing as this is not an issue with the plugin itself but with your build environment.

**Closed by dpa99c** 2017-11-17 08:51 UTC
