### ISSUE TITLE
It gets stuck when opening for the first time on iOS

### ISSUE THREAD

**Issue by blasco** [dpa99c/phonegap-launch-navigator#234] opened 2019-12-05 12:24 UTC
# Bug report

**Current behavior:**

It works perfectly fine in Android, but in iOS it gets stuck the first time you try to use it. If you reload the app, then it works fine, as it can be seen in the attached video

**Screenshots**

![copressed](https://user-images.githubusercontent.com/3214400/70235278-edad1a80-1762-11ea-8c38-3787a42251f9.gif)

**Environment information**

- Cordova CLI version 
	- `cordova -v`: 9.0.0
- Cordova platform version
	- `cordova platform ls` ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-crop 0.3.1 "CropPlugin"
cordova-plugin-datepicker 0.9.2 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.3 "ImagePicker"
cordova-plugin-whitelist 1.3.3 "Whitelist"
es6-promise-plugin 4.2.2 "Promise"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers` 
           productName: mac os x 
           productVersion: 10.14.6 
           buildVersion: 18g95

	
_iOS build issue:_
- Node JS version
    - `node -v`: 6.11.3
- XCode version: 11.1

**Related code:**
```
      this.launchNavigator.navigate([this.proDetails.additionalAddresses[i].latitude, this.proDetails.additionalAddresses[i].longitude], options).catch(error => {
          this.toastController.create({
            message: `Error: ${error}`,
            position: 'bottom',
            buttons: [
              {
                text: 'Ok'
              }
            ]
          }).then(toast => { 
            toast.present();
          });
      });

```

**Comment by dpa99c** [comment] 2019-12-05 12:47
Duplicate of #231

**Closed by dpa99c** 2019-12-05 12:47 UTC
