### ISSUE TITLE
navigate from launcher app to another app

### ISSUE THREAD

**Issue by kanishkamehta801** [dpa99c/phonegap-launch-navigator#129] opened 2017-05-12 06:03 UTC
Hello,

I had my app in the phone in which i have integrated the launcher navigation apps when click on some button but i want when my destination distance to be remain only 100 metres then the launcher navigation app will close and my app will open. 
So my ques is how can i get the real time coordinates in each 5 sec from launcher app and how can i move from launcher app to my app ?

Thanks in advance

**Comment by dpa99c** [comment] 2017-05-12 07:16
Duplicate of #112 and #127. No it's not possible.

**Closed by dpa99c** 2017-05-12 07:16 UTC

**Comment by kanishkamehta801** [comment] 2017-05-12 07:28
Thanks for you quick response!
