### ISSUE TITLE
Google Back Button Disappears After 15 seconds

### ISSUE THREAD

**Issue by KimberleeDArmstrong** [dpa99c/phonegap-launch-navigator#18] opened 2015-05-28 19:22 UTC
Thank you for the implementing the google preferred and having google call a url with a back button.  I was able to get it working and it works great. When you click the back button it takes me right back to my app, but the button goes away in Google Maps after 15 seconds.  Any ideas what could be causing that?

**Comment by dpa99c** [comment] 2015-05-29 07:18
@KimberleeDArmstrong While I've added the functionality to use x-callback with Google Maps, I haven't actually tested it yet which is why it's not documented. 
It sounds like the disappearing button you're seeing is intended behaviour Google has added to Google Maps, in which case there's not a lot we can do about it. When I get around to implementing an example using this functionality, I'll investigate further.

**Comment by KimberleeDArmstrong** [comment] 2015-05-29 14:15
Thanks for the reply.  It is still I nice feature for the "oops" 
clicks.  It gets you back easily if you accidentally click get 
directions.  Thank you!

**Comment by saurabhkrishnan09** [comment] 2015-06-15 10:56
Hi,

Thanks for creating such a nice navigator plugin.
Here this feature is of immediate requirement for me as this looks as a showstopper in my app.

I request you to please fix up this issue asap.

**Comment by dpa99c** [comment] 2015-06-15 11:11
@saurabhkrishnan09 The button disappearing in Google Maps after 15 seconds seems to be intended behaviour created by Google. There's no way the plugin can prevent Google Maps from doing this; the plugin simply uses a URL scheme to open the Google Maps app with the given source/destination locations. What happens after that is up to Google, so you might want to take it up with them :-)

**Comment by saurabhkrishnan09** [comment] 2015-06-15 13:41
Okay I understand that. I think we can achieve that similar thing, if  we have similar custom button in google map app on top of screen showing every-time. How this could be achieved I will search out tomorrow.

**Comment by dpa99c** [comment] 2015-06-15 13:50
I noticed Google have updated [their documentation](https://developers.google.com/maps/documentation/ios/urlscheme#add_navigation_to_your_app) with this notice:

"Note: Buttons added via the x-source parameter will not be displayed in the turn-by-turn navigation UI."

which kind of contradicts their navigation example which uses the x-source parameter

**Comment by dpa99c** [comment] 2015-09-21 19:09
iOS 9 has added a new feature so when an app launches another app, a "Back to {app name}" button automatically appears in the top-left corner of the screen (see screen captures below). This resolves the issue of getting back to your app on iOS for both Google Maps and Apple Maps and makes the back button parameter in the Google Maps x-callback scheme redundant.  I will deprecate and remove this functionality from the plugin in the next release, but will close this issue as iOS9 resolves it

![google_maps_ios9](https://cloud.githubusercontent.com/assets/2345062/10000386/b54a5656-6093-11e5-9dec-459b6bad6026.png)
![apple_maps_ios9](https://cloud.githubusercontent.com/assets/2345062/10000387/b54ba4de-6093-11e5-923c-70860a23a7b7.png)

**Closed by dpa99c** 2015-09-21 19:09 UTC

**Comment by inplamba** [comment] 2016-07-29 07:56
Hey @dpa99c
I am Using Launch Navigator ,Can this plugin provide success callback (Means when we reached the destination in google maps from starting point) it gives us success that user reached the destination

Thanks in Advance
