### ISSUE TITLE
Google maps suggest own path, every time user navigate google maps with stops through launch navigator

### ISSUE THREAD

**Issue by Astha-Anand** [dpa99c/phonegap-launch-navigator#246] opened 2020-05-26 09:22 UTC
# Bug report

**Current behavior:**

When navigate to google maps with selected stops using launch navigator, it suggest its own path and not the one we passed with launch navigator.

**Expected behavior:**

It should not suggest different paths on google maps, should only show the points we passed through launch navigator. Problem is google map not following path as the path in our app.

**Steps to reproduce:**

1. Bike rider redirected to google maps with 20+ selected stops through launch navigator
2. On google maps it show a different path not same as in app map

**Screenshots**

![image011](https://user-images.githubusercontent.com/53165103/82883681-6649a280-9f60-11ea-853d-217ac5e95c5e.png)

**Environment information**

- Cordova CLI version 
	- 9.0.0
- Cordova platform version
	- `cordova platform ls` . 
     Installed platforms:
          ios 5.1.1
     Available platforms: 
         android ^8.0.0
         browser ^6.0.0
         electron ^1.0.0
         osx ^5.0.0
         windows ^7.0.0
- Plugins & versions installed in project (including this plugin)
    uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
- Dev machine OS and version, e.g.
   MacOS Mojave 10.14.5

- Node JS version
    - v10.19.0
	
_iOS build issue:_
- Node JS version
    - v10.19.0
- XCode version - 10.2.1

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```
this.waypoints.map((waypoint, index) => {
          navigationString = navigationString.concat(
            `${waypoint.location.lat},${waypoint.location.lng}`
          );
          if (index < polylines.length - 1) {
            navigationString = navigationString.concat("+to:");
          }
        });

        if (this.platform.is("android")) {
          navigationString = escape(navigationString);
        } else {
          navigationString = navigationString.replace(/&/g, "AND");
        }
        console.log("encoded uri-->", navigationString);
        const destinationName = rideData.name;

        this.launchNavigator.availableApps().then((apps) => {
          console.log(apps);
        });
        launchnavigator.enableDebug(
          true,
          function(success: any) {
            console.log("Log enabled", success);
          },
          function(err: any) {
            console.log("Err enabled", err);
          }
        );

        this.launchNavigator
          .isAppAvailable(this.launchNavigator.APP.GOOGLE_MAPS)
          .then(
            (success)
 => {
              console.log("is Google maps available->", success);
              let app: any;
              if (success)
 {
                app = this.launchNavigator.APP.GOOGLE_MAPS;
              } else {
                console.warn("Google Maps not available");
                app = this.launchNavigator.APP.USER_SELECT;
              }
            
              const options: LaunchNavigatorOptions = {
                app,
                // start: latitude + "," + longitude,
                transportMode: this.launchNavigator.TRANSPORT_MODE.DRIVING,
                destinationName,
                extras: {},
              };
              if (this.avoidHighways) {
                options.extras.avoid = "highways";
              }

              this.launchNavigator.navigate(navigationString, options);
            },
            (err) => {
              console.log("App not aviaalble error", err);
            }
          );

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment] 2020-05-26 09:29
This is an exact duplicate of #245.
I have already made it clear that this behaviour is internal to the Google Maps app and this plugin has no control over it.
Do not open another duplicate issue or you will be banned.

**Closed by dpa99c** 2020-05-26 09:29 UTC

**Comment by dineshrawat11** [comment] 2020-05-26 09:37
I also tried to check same thing. I don't find any option to control this from this plugin. That is something related to Google map.
