### ISSUE TITLE
Plugin seems to terminate app process when invoked

### ISSUE THREAD

**Issue by joshbuchea** [dpa99c/phonegap-launch-navigator#6] opened 2015-02-18 20:39 UTC
I'm not sure if this is the expected behavior, but after calling the plugin and after the navigation loads, it seems to halt my app's process. If I continue pressing back to go back to my app, my app has restarted and loses it's current state.

I have very little native Android knowledge, is this expected behavior when invoking an ACTION_VIEW intent?

Testing on a Nexus 4 running Android 5.0.1.

**Comment by joshbuchea** [comment] 2015-02-19 01:35
So, originally I was calling launchnavigator.navigate from within navigation.geolocation.getCurrentPosition like so:
````
navigator.geolocation.getCurrentPosition(function(pos) {
  launchnavigator.navigate(
    [lat, lng],
    null,
    function(){
      console.log('It worked on Android!');
     },
     function(){
       console.log('Did not work on Android for some reason.');
     });
});. 
````
I wasn't using the position from getCurrentPosition(), but this caused my Android app to crash for some reason. Calling launchnavigator.navigate from outside of this seemed stopped the app from crashing.

Also, trying to get navigation directions with only a destination address failed when invoked with the navigate method like above.

But, invoking the deprecated navigateByLatLong method like so worked perfectly:
````
launchnavigator.navigateByLatLon(
  lat,
  lng,
  function(){
    console.log('It worked on Android!');
  },
  function(){
    console.log('Did not work on Android for some reason.');
  });
````

I'm working right now, but I'll try to take a look later and see if I can figure out where the issue is. Thanks for the plugin BTW. After some fiddling, works great!

**Comment by dpa99c** [comment] 2015-02-19 07:39
Hi Josh,

Thanks for your comments. I only wrote the new navigate() implementation last night, and while I gave it a brief test on Android using the example project, it may be that there is an issue with it. I too am at work right now, but I'll have a look tonight. If you do find any more detail about where the issue is, any info would be much appreciated, or if you fixed it yourself, just make a pull request and I'll patch in your changes.

Thanks,
Dave

**Comment by opadro** [comment] 2015-02-20 03:04
Josh

Are you using the `org.apache.cordova.geolocation` plugin? If I don’t include this plugin the code below never executes. It works fine if I use the plugin. The app never hangs in either case thought. I tested this on my HTC Desire 610 (KitKat).


```
 $("#go4").click(function () {

                    console.log('inside click');
                    navigator.geolocation.getCurrentPosition(function (pos) {
                        console.log('position found');
                        launchnavigator.navigate(
                                [lat_close_home, lng_close_home],
                                null,
                                function () {
                                    console.log('It worked on Android!');
                                },
                                function () {
                                    console.log('Did not work on Android for some reason.');
                                });
                    });
                });

```

Oscar

**Comment by dpa99c** [comment] 2015-04-14 10:04
On Android, once your app is put into the background it is at the mercy of Android's garbage collection. If there's lots of other apps running or resources are running low, Android may decide to terminate your app's process since it is no longer in the foreground (the navigation app is). One possible workaround is for your app to acquire a [partial wakelock](http://developer.android.com/reference/android/os/PowerManager.html#PARTIAL_WAKE_LOCK) before calling the plugin in order to keep it alive in the background. This can be released when your app resumes.
Closing this issue as it is not specifically related to this plugin

**Closed by dpa99c** 2015-04-14 10:04 UTC
