### ISSUE TITLE
Installation on cordova 7.1.0 not finding AndroidManifest.xml

### ISSUE THREAD

**Issue by reyx** [dpa99c/phonegap-launch-navigator#205] opened 2018-09-16 20:27 UTC
**I'm submitting a**:
- [x] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**
On a clean project using cordova 8.0.0, when trying to install plugin with cordova-android 7.1.0 the installation fails with message :

Error: ENOENT: no such file or directory, open 'D:\projects\cordova\bateclick-app\platforms\android\AndroidManifest.xml'

I believe this plugin was not designed to work with cordova-android >= 7. Is this correct?

**Expected behavior:**

Terminal fails with message :

Error: ENOENT: no such file or directory, open 'D:\projects\cordova\bateclick-app\platforms\android\AndroidManifest.xml'

**Steps to reproduce:**
On projects root:

```
ionic cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator@4.2.2
```      
	
_Android build issue:_	
- Node JS version
    - v8.11.3
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- 27
- Android SDK details
    ```
    Installed packages:
    Path                              | Version | Description                       | Location
    -------                           | ------- | -------                           | -------
    add-ons;addon-g..._apis-google-23 | 1.0.0   | Google Apis, Android 23           | add-ons\addon-g...apis-google-23\
    build-tools;23.0.3                | 23.0.3  | Android SDK Build-Tools 23.0.3    | build-tools\23.0.3\
    extras;android;m2repository       | 41.0.0  | Android Support Repository, re... | extras\android\m2repository\
    platform-tools                    | 25.0.3  | Android SDK Platform-Tools 25.0.3 | platform-tools\
    platforms;android-23              | 3       | Android SDK Platform 23, rev 3    | platforms\android-23\
    platforms;android-27              | 1       | Android SDK Platform 27           | platforms\android-27\
    system-images;a...pis;armeabi-v7a | 19      | Google APIs ARM EABI v7a Syste... | system-images\a...is\armeabi-v7a\
    system-images;a...google_apis;x86 | 19      | Google APIs Intel x86 Atom Sys... | system-images\a...oogle_apis\x86\
    tools                             | 25.2.5  | Android SDK Tools 25.2.5          | tools\

    Available Packages:
    ```

_If using an [Ionic Native Typescript wrapper]() for this plugin:_
- Ionic environment info
    ```
    Ionic:

       ionic (Ionic CLI)  : 4.1.2 (C:\Users\regis\AppData\Roaming\npm\node_modules\ionic)
       Ionic Framework    : ionic-angular 3.9.2
       @ionic/app-scripts : 3.1.11

    Cordova:

       cordova (Cordova CLI) : 8.0.0
       Cordova Platforms     : android 7.1.0
       Cordova Plugins       : cordova-plugin-ionic 5.1.5, cordova-plugin-ionic-keyboard 2.1.2, cordova-plugin-ionic-webview 2.1.3, (and 15 other plugins)

    System:

       Android SDK Tools : 26.1.1 (D:\Android\sdk)
       NodeJS            : v8.11.3 (D:\nodejs\node.exe)
       npm               : 6.4.1
       OS                : Windows 10
    ``´

- Installed Ionic Native modules and versions     
    ```
    +-- @ionic-native/core@4.11.0
    +-- @ionic-native/launch-navigator@4.11.0ERR!
    +-- @ionic-native/native-page-transitions@4.11.0
    +-- @ionic-native/splash-screen@4.11.0
    +-- @ionic-native/status-bar@4.11.0
    ```

**Console output**

<details>
<summary>console output</summary>

```
> cordova plugin add uk.co.workingedge.phonegap.plugin.launchnavigator@4.2.2 --save
Installing "uk.co.workingedge.phonegap.plugin.launchnavigator" for android
Plugin dependency "cordova-plugin-actionsheet@2.3.3" already fetched, using that version.
Dependent plugin "cordova-plugin-actionsheet" already installed on android.
Plugin dependency "cordova-plugin-dialogs@2.0.1" already fetched, using that version.
Dependent plugin "cordova-plugin-dialogs" already installed on android.
Failed to install 'uk.co.workingedge.phonegap.plugin.launchnavigator': Error: ENOENT: no such file or directory, open 'D:\projects\cordova\bateclick-app\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (D:\projects\cordova\bateclick-app\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (D:\projects\cordova\bateclick-app\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (D:\projects\cordova\bateclick-app\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (D:\projects\cordova\bateclick-app\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
(node:20404) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'D:\projects\cordova\bateclick-app\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync (D:\projects\cordova\bateclick-app\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest (D:\projects\cordova\bateclick-app\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName (D:\projects\cordova\bateclick-app\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (D:\projects\cordova\bateclick-app\platforms\android\cordova\Api.js:223:57)
    at handleInstall (C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:20404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
handled with .catch(). (rejection id: 1)
(node:20404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at self.promiseDispatch.done (C:\Users\regis\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
```
</details><br><br>

**Comment by dpa99c** [comment] 2018-09-16 21:10
Duplicate of #203

**Closed by dpa99c** 2018-09-16 21:10 UTC
